
[workspace]
members = [
  "crates/serwave-app",
  "crates/serwave-core",
  "crates/serwave-decode",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/lich0821/SerWave"
authors = ["SerWave Contributors"]
