
[workspace]
members = [
  "crates/serwave-app",
  "crates/serwave-core",
  "crates/serwave-decode",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/serwave/serwave"
