
[package]
name = "serwave-core"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
serialport = "4"
thiserror = "1"
log = "0.4"
parking_lot = "0.12"
crossbeam-channel = "0.5"
encoding_rs = "0.8"
chardetng = "0.1"
